version: "3"
services:
  openq-coinapi:
    container_name: openq-coinapi
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./
    ports:
      - "8081:8081"
    volumes:
      - /app/node_modules
      - ./:/app
    env_file:
      - ./.env
  redis:
    container_name: redis
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
